### ISSUE TITLE
Atualização do Mysql-Client

### ISSUE THREAD

**Issue by arthurd2** [tainacan/tainacan-docker#1]
O Build da problema ao instalar o "mysql-client".
Me parece que a imagem docker do WORDPRESS foi atualizada e não existe mais o pacote "mysql-client".
Agora é "default-mysql-client".

**Comment by leogermani** [comment]
@vnmedeiros pode dar uma olhada?

**Comment by vnmedeiros** [comment]
vou verificar, não tinha passado por isso.

**Comment by vnmedeiros** [comment]
boa tarde @arthurd2
O probelma foi solucionado, aproveito para informar que a imagem já compilada está disponível no dockhub:

https://hub.docker.com/r/tainacan/tainacan
