### ISSUE TITLE
Docker error on start: Cannot create container for service wordpress: missing device in volume options

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan-docker#10]
hi, I guess additional config is needed on my part – I get the following error after running

```
./tainacan.sh --clone
./tainacan.sh --build-image
./tainacan.sh --start
```

No errors after the first two commands, but after the third (--start):

```
[START TAINACAN]
WARNING: The LOCAL_PATH variable is not set. Defaulting to a blank string.
WARNING: The WEB_APP_PATH variable is not set. Defaulting to a blank string.
Creating network "dev_default" with the default driver
Creating mysql_tainacan ... done
Creating tainacan-dev   ... error

ERROR: for tainacan-dev  Cannot create container for service wordpress: missing device in volume options

ERROR: for wordpress  Cannot create container for service wordpress: missing device in volume options
```

**Comment by Ambrosiani** [comment]
…so I guess I should enter LOCAL_PATH and WEB_APP_PATH somewhere? Not a very experienced Docker user…

**Comment by vnmedeiros** [comment]
Hi @Ambrosiani 
this docker installation needs two environment variables to be able to mount the volumes correctly:

- **LOCAL_PATH**: full path to the installation folder 
- **WEB_APP_PATH**: folder in which the volume will be created with the installation of the WP 

To make it easier you can create an .env file at the root of the directory with the values of the variables, for example :

```
LOCAL_PATH=/home/user/tainacan-docker/dev
WEB_APP_PATH=/www
```
