### ISSUE TITLE
Erro de IMAGICK ja instalado

### ISSUE THREAD

**Issue by arthurd2** [tainacan/tainacan-docker#2]
Ao dar build, o seguinte comando gera erro, pois o pacote ja esta instalado.
Isto é um problema na automação pois ferramentas de CI/CD consideram isto uma falha no pipeline e quebram o job.
```yml
RUN yes | pecl install imagick
```

**Comment by leogermani** [comment]
Sim, a gente tem enfrentado esse problema.

Aparentemente acontecia quando já tinha uma outra imagem com o mesmo nome (wordpress) na máquina. @vnmedeiros pode dar mais detalhes e ver como a gente resolve.

Hoje em dia a gente comenta essa linha na hora de dar o build. Mas não podemos tirar pq quando damos o build em uma máquina zerada ela faz falta...

**Comment by vnmedeiros** [comment]
Sim a solução mais rapida é comentar/remover a linha no arquivo `Dockerfile`, parece que a imagem do wordpress/php já está vindo com esse modulo instalado e o *pecl* ao invez de apenas ignorar, gera um erro que faz com que o build não continue, devo atualizar o dockefile para evitar essa falha. 

obrigado!

**Comment by vnmedeiros** [comment]
boa tarde @arthurd2
O probelma foi solucionado, aproveito para informar que a imagem já compilada está disponível no dockhub:

https://hub.docker.com/r/tainacan/tainacan
